---
title: 'Between sample analysis: composition of the communities'
author: "Yining Sun"
date: "`r format(Sys.time(), '%B %d %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: united
    highlight: tango
editor_options: 
  chunk_output_type: console
---

# load packages
```{r}
# efficiently load packages
pacman::p_load(phyloseq, iNEXT, ggpubr, tidyverse, vegan, install = FALSE)

# be in the right place
setwd("/local/workdir/ys636/BIOMI6300_Amplicon_Analysis")

# load functions and color preferences
source("./code/functions.R")
source("./code/colors_and_shapes.R")
```


# load data
```{r load-data}
load("./data/preprocessed_physeq.RData")
preprocessed_physeq

# what are the sample size distributions?
preprocessed_physeq %>%
  # prune_samples(sample_sum(.) > 2000, .) %>%
  sample_sums() %>%
  data.frame() %>%
  View()

# remove sample that has the fewest number of reads
# the fewest reads is 1839 and the next is 2267
# o decided to use those extra 400 reads for more accurate beta diversity
physeq_2267 <- preprocessed_physeq %>%
  prune_samples(sample_sums(.) > 2000, .)

```


# Types of normalization
## 1. subset 
## 2.  subset * N (N=1000) - rarefy
## 3. "Scale": counts asv | total counts samples * min (total counts dataset)


# normalize the reads
## scale the read counts
```{r scale-reads}
set.seed(2000)

# scale the reads using function scale_reads from functions.R

# intuition check of number of seqeunces per sample
min(sample_sums(physeq_2267))

scaled_physeq2267 <-  
  physeq_2267 %>%
  scale_reads(round = "matround")

# Now check the sequencing depth! 
scaled_seqSums_df <-   
scaled_physeq2267 %>%  
otu_table(.) %>%  # Take the sum of the sample abundance   
colSums(.) %>%  
data.frame() %>%  
rownames_to_column(., var = "names") %>% 
 make_MA_metadata()
 
 # Rename the 2nd column 
 colnames(scaled_seqSums_df)[2] <- "TotalSeqs"   
 
 # Plot the histogram
 scaled_seqSums_df %>%  
 ggplot(aes(x=TotalSeqs)) + #fill = fraction   
 ggtitle("Histogram of Raw Read Counts Samples") +  
 geom_histogram(bins = 50) + 
 theme(legend.position = c(0.15, 0.85)) +   
 scale_y_continuous(expand = c(0,0)) +   
 scale_x_continuous(limits = c(2200, 3000)) # PLAY AROUND WITH NUMBERS!  #scale_fill_manual(values = fraction_colors)

```


# PCoA
```{r}
# calculate Bray-curtis Dissimilarity
scaled_BC_pcoa <-
  ordinate(
    physeq = scaled_physeq2267,
    method = "PCoA",
    distance = "bray",
    binary = FALSE
  )

# ordiate-measures some distance


# plot the PCoA
plot_ordination(
  physeq = scaled_physeq2267, 
  ordination = scaled_BC_pcoa,
  color = "fraciton",
  shape = "fraction",
  title = "Scaled Bray-Curtis PCoA") +
  geom_point(size = 5, alpha = 0.5, aes(color = fraction)) +
  scale_color_manual(values = fraction_colors)


# plot the PCoA
plot_ordination(
  physeq = scaled_physeq2267, 
  ordination = scaled_BC_pcoa,
  color = "station",
  shape = "station",
  title = "Scaled Bray-Curtis PCoA") +
  geom_point(size = 5, alpha = 0.5, aes(color = station)) +
  scale_color_manual(values = station_colors)


## both x-axis and y-axis represent eigen values

```


# stats
# check for difference in the cummunities using PERMANOVA
```{r permanova}
# calculate bray curtis for permanova
scaled_bray <- phyloseq::distance(scaled_physeq2267, method = "bray", binary = FALSE)

# pull out metadata
metadata <- scaled_physeq2267 %>%
  sample_data() %>%
  data.frame()


# permutational multivariate analysis of variance using distance matrices
# aka PERMANOVA using the adonis2 function form vegan
# test the hypothesis that the fraction centroids are different using the bray curtis
# test if the centroids of the fractions are different
adonis2(scaled_bray ~ fraction, data = metadata)


# are th ecentroids different for stations based on bray curtis
adonis2(scaled_bray ~ station, data = metadata)
### station explained around 40% of the data 


# date
adonis2(scaled_bray ~ date, data = metadata) # missing value

# are they independent of each other?
adonis2(scaled_bray ~ station + fraction, data = metadata)

# is there an interaction between the variables?
adonis2(scaled_bray ~ station * fraction, data = metadata)


```



# homogeniety of dispersion test: beta disper
```{r}
# dispersion between stations
betadispr_station <- betadisper(scaled_bray, metadata$station)
permutest((betadispr_station))

```

# compositional analysis
```{r}
phylum_df <- 
  scaled_physeq2267 %>%
  tax_glom(taxrank = "Phylum") %>% # agglomerate/merge counts by phylum
  transform_sample_counts(function(x) {x/sum(x)}) %>% # transform to relative abundances
  psmelt() %>%         # melt into long format dataframe
  dplyr::filter(Abundance > 0.01)    # filter out phyla that are > 1% abundant
       
# plot the phylum distributions
phylum_df %>%
  dplyr::filter(depth == "S") %>%
  ggplot(aes(x = fraction, y = Abundance, fill = Phylum)) +
  geom_bar(stat = "identity", color = "black") +
  facet_grid(~station) +
  scale_fill_manual(values = phylum_colors)


```

